Skillbag/Skillbag/urls.py

# Django
from django.urls import include
from django.urls import path, re_path
from django.contrib import admin
from django.views.generic import TemplateView

# Local
from categories import views as category_views
from skills import views as skill_views
from nexus import views as nexus_views


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', TemplateView.as_view(template_name='nexus/page-nexus.html'), name='home'),
    re_path(r'^bag/(?P<slug>.+)', nexus_views.NexusWithArgumentsView.as_view(), name='smth'),
    path('403/', TemplateView.as_view(template_name='403.html'), name='403'),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
     
    path('accounts/', include('accounts.urls')),
    path('categories/', include('categories.urls')),
    path('skills/', include('skills.urls')),
    path('statistics/', include('stats.urls')),
    path('search/', include('search.urls')),
]

Skillbag/accounts/urls.py

# Django
from django.contrib.auth import views as auth_views
from django.urls import path

# Local
from accounts.views import views_account
from accounts.views import views_registration
from accounts.views import teams as views_teams
from accounts import forms
from skills.views import views_skills

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',authentication_form=forms.LoginForm), name='login'),
    path('register/', views_registration.SignupView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

    path('email-preferences/', views_account.EmailPreferencesView.as_view()),
    path('change-password/', views_account.ChangePasswordView.as_view()),

    path('teams/', views_teams.TeamChoiceView.as_view()),
    path('teams/add/', views_teams.AddTeamFormView.as_view()),
    path('teams/<team_name>/', views_skills.TeamSkillsView.as_view()),
    path('teams/<team_name>/admin/', views_teams.TeamAdminView.as_view()),
    path('teams/<team_name>/dashboard/', views_teams.TeamDashboardView.as_view()),
    
    path('teams/<team_name>/query-member/<query>/', views_teams.TeamInvitableMembersFetcherView.as_view()),
    path('teams/<team_name>/invite-member/', views_teams.TeamInviteUserView.as_view()),
    path('teams/<team_name>/accept-invitation/<invitation_code>/', views_teams.TeamInvitationAcceptView.as_view(), name='invitation-accept'),
    path('teams/<team_name>/remove-member/', views_teams.TeamRemoveUserView.as_view()),
    path('teams/<team_name>/toggle-admin/', views_teams.TeamToggleAdministratorStateView.as_view()),

    path('teams/<team_name>/query-skill/<query>/', views_teams.TeamAddeableSkillsFetcherView.as_view()),
    path('teams/<team_name>/add-skill/', views_teams.TeamAddSkillView.as_view()),
    path('teams/<team_name>/remove-skill/', views_teams.TeamRemoveSkillView.as_view()),
]

Skillbag/stats/urls.py

from django.urls import path
from stats import views

app_name = 'stats'

urlpatterns = [
    path('', views.HubView.as_view()),        
    
    # Personal Statistics
    path('personal/', views.PersonalStatsView.as_view()),
    path('personal/macrocategory-radar/', views.MacrocategoryRadarView.as_view()),
    path('personal/category-radar/', views.CategoryRadarView.as_view()),
    path('personal/completion-trend/', views.CompletionTrendView.as_view()),
    path('personal/proficiency-polar/', views.ProficiencyPolarView.as_view()),
]

Skillbag/nexus/models/abstract.py

# Python
import random
import datetime

# Django
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Local
from nexus.proxies import wikipediaProxy, PageParsingError 

class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class DescriptableMixin(models.Model):
    description = models.CharField(_("Description"), max_length=300, blank=True, null=True, default=None)
    wikipedia_link = models.CharField(_("Wikipedia Link"), max_length=200, blank=True, null=True, default=None)
    
    cached_wikipedia_summary = models.CharField(max_length=512, blank=True, null=True, default=None)
    cached_wikipedia_link = models.CharField(max_length=200, blank=True, null=True, default=None)
    wikipedia_cache_validity_date = models.DateTimeField(null=True, default=None)

    class Meta:
        abstract = True

    def get_description_or_summary(self, sentences=3):
        if self.description:
            return self.description
        if self.wikipedia_link:
            return self.get_description_from_wikipedia_or_cache(sentences=sentences)    
        return ""

    def get_description_from_wikipedia_or_cache(self, sentences=3):
        if self.cached_wikipedia_summary and timezone.now() < self.wikipedia_cache_validity_date and self.cached_wikipedia_link == self.wikipedia_link:
            return self.cached_wikipedia_summary
        else:
            try:
                wiki_summary = wikipediaProxy.summary_from_url(self.wikipedia_link, sentences=sentences)
                self.cached_wikipedia_summary = (wiki_summary[:497] + '..') if len(wiki_summary) > 500 else wiki_summary
                self.cached_wikipedia_link = self.wikipedia_link
                self.wikipedia_cache_validity_date = timezone.now() + datetime.timedelta(minutes=random.randint(43000, 47000))
                self.save()

                return self.cached_wikipedia_summary 
            except PageParsingError:
                return _("Error while parsing the Wikipedia page :(.\nIt seems the URL is not correct.")

        return ""

Skillbag/nexus/forms/forms_descriptable.py
    
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext as _

class DescriptableForm(ModelForm): 

    class Meta:
        fields = ['name', 'wikipedia_link', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['required'] = True
        self.fields['name'].widget.attrs['class'] = "editor-form__text-field editor-form__text-field--title"
        self.fields['name'].widget.attrs['placeholder'] = _('Name')
        
        self.fields['wikipedia_link'].widget.attrs['required'] = False
        self.fields['wikipedia_link'].widget.attrs['class'] = "editor-form__text-field"
        self.fields['wikipedia_link'].widget.attrs['placeholder'] = _('Wikipedia Link')
        self.fields['wikipedia_link'].widget.attrs['maxlength'] = "200"
        self.fields['wikipedia_link'].help_text = _('Always fill this field if possible. In case there is no description, the Wikipedia article will be used.')
        
        self.fields['description'].widget = forms.Textarea()
        self.fields['description'].widget.attrs['required'] = False
        self.fields['description'].widget.attrs['class'] = "editor-form__long-text-field"
        self.fields['description'].widget.attrs['placeholder'] = _('Description')
        self.fields['description'].widget.attrs['maxlength'] = "300"
        self.fields['description'].widget.attrs['rows'] = "6"        
        self.fields['description'].help_text = _('Fill this field only if there is no Wikipedia link or you feel you can write a better description.') 
    
    def clean_wikipedia_link(self):
        link = self.cleaned_data.get('wikipedia_link', None)
        if link and "wikipedia.org/wiki" not in link:
            raise forms.ValidationError("Are you sure this is a Wikipedia link?")
        return link

Skillbag/nexus/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class NexusWithArgumentsView(TemplateView):
    template_name = 'categories/categories.html'
    
    def get(self, request, *args, **kwargs):
        parameters = kwargs['slug']
        if not parameters:
            return redirect("/404/")
                
        parameters = parameters.split("/")
        page = parameters[0]
        arguments = parameters[1:]

        if not page.startswith("Page"):
            return redirect("/404/")
        
        query_params = "?page=" + page
        if arguments:
            query_params += "&args=" + "/".join(arguments)

        url = reverse("home") + query_params
        return redirect(url)

Skillbag/nexus/templates/nexus/fragments/fragment-disabled-entry.html
<div class="side-menu__entry side-menu__entry--disabled">
    <span style="margin-left: 25px" > {{ entry_text }}</span>
    <div class="side-menu__info">
        {% include 'nexus/svg/info-icon.html' %}
        <div class="side-menu__popup">{{ entry_popup_text }}</div>
    </div>
</div>

Skillbag/nexus/templates/nexus/fragments/fragment-editor-container.html
<div class="editor-container" id="editor-container">
    <div class="editor-container__outer-dialog">
        <div class="editor-container__inner-dialog">
            
            <div class="editor-container__editor-title" name="editor-title">
                Resources & Co.
            </div>

            <div class="editor-container__content">

            </div>

            <div class="editor-container__action-buttons">
                <div class="editor-container__back-button">
                    {% include '../svg/back-icon.html' %}
                </div>
                <div class="editor-container__confirm-button">
                    {% include '../svg/confirm-icon.html' %}
                </div>
            </div>
        </div>
    </div>
</div>


Skillbag/nexus/templates/nexus/fragments/fragment-messaging.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'nexus/content/messages.css' %}"/>

<div class="messages-container">
</div>

<template id="message-template">
    <div class="message">
        <span></span>
    </div>
</template>

<script src="{% static 'nexus/scripts/utils/MessageManager.js' %}"></script>

Skillbag/nexus/templates/nexus/fragments/loader.html

<div id="page-loader" class="loader">
</div>

Skillbag/nexus/templates/nexus/fragments/search-bar-with-dumper.html

<div style="margin-bottom: 100px">
    {% include "./search-bar.html" %}
</div>

Skillbag/nexus/templates/nexus/fragments/search-bar.html

<div class="search-bar">
    <input type="text" class="search-bar__input-field"/>
    <div class="search-bar__search-icon" style="z-index: 1; transform: scale(1);">
        <svg viewBox="0 0 512 512">
            <path d="M505.749,475.587l-145.6-145.6c28.203-34.837,45.184-79.104,45.184-127.317c0-111.744-90.923-202.667-202.667-202.667
					S0,90.925,0,202.669s90.923,202.667,202.667,202.667c48.213,0,92.48-16.981,127.317-45.184l145.6,145.6
					c4.16,4.16,9.621,6.251,15.083,6.251s10.923-2.091,15.083-6.251C514.091,497.411,514.091,483.928,505.749,475.587z
					M202.667,362.669c-88.235,0-160-71.765-160-160s71.765-160,160-160s160,71.765,160,160S290.901,362.669,202.667,362.669z"/>
        </svg>
    </div>    
    <div class="search-bar__cancel-icon" style="z-index: 1; transform: scale(0);">
        <svg style="transform: scale(0.8)" viewBox="0 0 329 329">
            <path d="m194.800781 164.769531 128.210938-128.214843c8.34375-8.339844 8.34375-21.824219 0-30.164063-8.339844-8.339844-21.824219-8.339844-30.164063 0l-128.214844 128.214844-128.210937-128.214844c-8.34375-8.339844-21.824219-8.339844-30.164063 0-8.34375 8.339844-8.34375 21.824219 0 30.164063l128.210938 128.214843-128.210938 128.214844c-8.34375 8.339844-8.34375 21.824219 0 30.164063 4.15625 4.160156 9.621094 6.25 15.082032 6.25 5.460937 0 10.921875-2.089844 15.082031-6.25l128.210937-128.214844 128.214844 128.214844c4.160156 4.160156 9.621094 6.25 15.082032 6.25 5.460937 0 10.921874-2.089844 15.082031-6.25 8.34375-8.339844 8.34375-21.824219 0-30.164063zm0 0"/>
        </svg>
    </div>
</div>

Skillbag/nexus/templates/nexus/fragments/side-menu.html
<div class="side-menu hidden" id="menu-container">
    
    <div id="close-menu-button" class="side-menu__menu-button">
        {% include '../svg/site-menu.html' %}
    </div>

    {% if user.is_authenticated %}
        <!-- Welcome message-->
        <span class="side-menu__welcome-message" id="account-settings-link" data-destination="PageChangePassword"> 
            Welcome<br/>{{ user.email }}             
        </span>
    {% endif %}

    <div class="side-menu__entries-container">

        {% if user.is_authenticated %}
        
            <!-- Menu Entries (Authenticated) -->
            <div class="side-menu__entry" data-destination="PageSearch">Home</div>
            <div class="side-menu__entry" data-destination="PageMySkills">My Skills</div>
            <div class="side-menu__entry" data-destination="PageAllSkills">Most Popular Skills</div>
            <div class="side-menu__entry" data-destination="PageMacrocategories">Categories</div>
            <div class="side-menu__entry" data-destination="PageStatisticsHub"> Statistics </div>
            <div class="side-menu__entry" data-destination="PageTeamSelection"> Teams </div>
            <a class="side-menu__entry side-menu__entry--align-bottom" href="{% url 'accounts:logout' %}">Logout</a>
            
        {% else %}

            <!-- Menu Entries (Not authenticated) -->
            <a class="side-menu__entry" href="/">Home</a>
        
            {% include './fragment-disabled-entry.html' with entry_text="My Skills" entry_popup_text="Register for free to see your skills" %}
            {% include './fragment-disabled-entry.html' with entry_text="Most Popular Skills" entry_popup_text="Register for free to see the most popular skills in Skillbag" %}
            {% include './fragment-disabled-entry.html' with entry_text="Categories" entry_popup_text="Register for free to access all categories" %}
            {% include './fragment-disabled-entry.html' with entry_text="Statistics" entry_popup_text="Register for free to access the statistics" %}
            {% include './fragment-disabled-entry.html' with entry_text="Teams" entry_popup_text="Register for free to use the team functionality" %}

            <div style="margin: 50px"></div>
            <a class="side-menu__entry" href="{% url 'accounts:register' %}">Register</a>
            <a class="side-menu__entry" href="{% url 'accounts:login' %}">Login</a>
        
        {% endif %}

    </div>

</div>